/*
 * robotDefines.h
 *
 *  Created on: Jun 10, 2014
 *      Author: Cyril Jourdan
 */

#ifndef ROBOTDEFINES_H_
#define ROBOTDEFINES_H_

//#define TRS_DEBUG
//#define BUILD_FOR_NEXUS_7
//#define BUILD_FOR_SURFACE_PRO_2

#define NUMBER_MAX_EPOS2_PER_SLAVE 		15
#define NUMBER_SLAVE_BOARDS         	5
#define NUMBER_OF_MOTORS				NUMBER_MAX_EPOS2_PER_SLAVE*NUMBER_SLAVE_BOARDS //75

#define SLAVE_LEFT_ARM_ID		1
#define SLAVE_RIGHT_ARM_ID		2
#define SLAVE_HEAD_ID			3
#define SLAVE_LEFT_LEG_ID		4
#define SLAVE_RIGHT_LEG_ID		5

#define HEART_BEAT				25

//CONTROL MODES
#define NO_MODE					-1 //0xFF
#define POSITION_MODE			0
#define CURRENT_MODE			1
#define VELOCITY_MODE			2
#define SERVO_POS_MODE			3

//NODE IDs
//Slave : Left Arm
#define LEFT_ARM_BICEPS_ID		1 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_SUPRA_ID		2 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_INFRA_ID		3 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_TMIN_ID		4 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_5_ID			5 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_SUBSCAP_ID		6 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_ANTDELT_ID		7 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_LATDELT_ID		8 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_POSTDELT_ID	9 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_BRACHI_ID		10 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_TRICEPS_ID		11 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_12_ID			12 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_HAND_ID		13 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_14_ID			14 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_ARM_ROTATOR_ID		15 + (SLAVE_LEFT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE

//Slave : Right Arm
#define RIGHT_ARM_BICEPS_ID		1 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_SUPRA_ID		2 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_SUBSCAP_ID	3 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_INFRA_ID		4 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_TMIN_ID		5 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_LATDELT_ID	6 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_ANTDELT_ID	7 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_POSTDELT_ID	8 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_TRICEPS_ID	9 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_BRACHI_ID		10 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_HAND_ID		11 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_ROTATOR_ID	12 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_13_ID			13 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_14_ID			14 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_ARM_15_ID			15 + (SLAVE_RIGHT_ARM_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE

//Slave : Head
#define HEAD_1_ID			1 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_2_ID			2 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_3_ID			3 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_4_ID			4 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_5_ID			5 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_6_ID			6 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_7_ID			7 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_EYE_PITCH_ID	8 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_EYE_YAW_ID		9 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_EYE_ROLL_ID	10 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_EYE_IRIS_ID	11 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_NECK7_ID		12 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_NECK8_ID		13 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_NECK9_ID		14 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define HEAD_NECK10_ID		15 + (SLAVE_HEAD_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE

//Slave4 : Left Leg
#define LEFT_LEG_ILIAS_ID				1 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_INNER_GLUT_MIN_ID		2 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_OUTER_GLUT_MIN_ID		3 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_OBTURATOR_ID			4 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_GLUT_MAX_ID			5 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_GLUT_MED_ID			6 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_RECTUS_FEMORIS_ID		7 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_8_ID					8 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_ADDUCTOR_ID			9 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_QUADRICEPS_ID			10 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_TIBALIS_ANTERIOR_ID	11 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_LATERAL_OUTER_GAST_ID	12 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_MEDIAL_OUTER_GAST_ID	13 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_MEDIAL_INNER_GAST_ID	14 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define LEFT_LEG_LATERAL_INNER_GAST_ID	15 + (SLAVE_LEFT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE

//Slave5 : Right Leg
#define RIGHT_LEG_ILIAS_ID				1 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_INNER_GLUT_MIN_ID		2 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_OUTER_GLUT_MIN_ID		3 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_OBTURATOR_ID			4 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_GLUT_MAX_ID			5 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_GLUT_MED_ID			6 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_RECTUS_FEMORIS_ID		7 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_8_ID					8 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_ADDUCTOR_ID			9 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_QUADRICEPS_ID			10 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_TIBALIS_ANTERIOR_ID	11 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_LATERAL_OUTER_GAST_ID	12 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_MEDIAL_OUTER_GAST_ID	13 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_MEDIAL_INNER_GAST_ID	14 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE
#define RIGHT_LEG_LATERAL_INNER_GAST_ID	15 + (SLAVE_RIGHT_LEG_ID-1)*NUMBER_MAX_EPOS2_PER_SLAVE

#define FIRST_SERVO_ID			38

#endif /* ROBOTDEFINES_H_ */
